# Create Vm and Using ansible to deloy application in playbook
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"                                    # vagrant box ubuntu 20.04
  config.vm.network "private_network", ip: "192.168.56.4"             # Config network of host
  config.vm.define "zabbix-server"                                    # Use this to define svr name

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = 1
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"  #  playbook's name Ansible
end
end
