---
zabbix:
  hosts:
    zabbix1:
      ansible_host: 192.168.56.4
      ansible_user: vagrant
      ansible_ssh_private_key_file: ~/.vagrant.d/insecure_private_key
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
